# Generated by Django 3.2.4 on 2021-10-16 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('payment_option', models.CharField(blank=True, default='razorpay', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_paid', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('order_key', models.CharField(max_length=200)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('isrefundrequested', models.BooleanField(default=False)),
                ('isrefundgranted', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Returned', 'Returned')], default='Pending', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=3, error_messages={'name': {'max_length': 'Selling Price must be numeric value greater than 0'}}, help_text='Selling Price must be numeric value greater than 0', max_digits=12, verbose_name='Selling Price Inclusive of tax')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='razorpay_payment_gateway.order')),
            ],
        ),
    ]
